//传进来测量位置-10
//然后再-10
//滑块起始位置到滑动结束位置距离 - 10
var arr = [
    [
        64,
        303,
        2
    ],
    [
        0,
        0,
        109
    ],
    [
        1,
        0,
        18
    ],
    [
        1,
        0,
        8
    ],
    [
        1,
        0,
        2
    ],
    [
        1,
        0,
        7
    ],
    [
        1,
        0,
        4
    ],
    [
        1,
        0,
        21
    ],
    [
        0,
        0,
        1
    ],
    [
        4,
        0,
        0
    ],
    [
        1,
        0,
        2
    ],
    [
        1,
        0,
        4
    ],
    [
        1,
        0,
        3
    ],
    [
        1,
        0,
        4
    ],
    [
        1,
        0,
        1
    ],
    [
        0,
        -1,
        2
    ],
    [
        1,
        0,
        0
    ],
    [
        0,
        0,
        3
    ],
    [
        1,
        0,
        3
    ],
    [
        1,
        0,
        2
    ],
    [
        1,
        0,
        1
    ],
    [
        1,
        0,
        3
    ],
    [
        0,
        -1,
        2
    ],
    [
        1,
        0,
        0
    ],
    [
        1,
        0,
        4
    ],
    [
        1,
        0,
        1
    ],
    [
        1,
        0,
        4
    ],
    [
        1,
        0,
        2
    ],
    [
        1,
        0,
        1
    ],
    [
        0,
        -1,
        2
    ],
    [
        0,
        0,
        2
    ],
    [
        1,
        0,
        1
    ],
    [
        0,
        0,
        2
    ],
    [
        1,
        0,
        1
    ],
    [
        1,
        0,
        2
    ],
    [
        1,
        0,
        5
    ],
    [
        1,
        0,
        1
    ],
    [
        1,
        0,
        1
    ],
    [
        1,
        0,
        2
    ],
    [
        1,
        -1,
        0
    ],
    [
        1,
        0,
        3
    ],
    [
        1,
        0,
        2
    ],
    [
        0,
        0,
        1
    ],
    [
        1,
        0,
        0
    ],
    [
        2,
        0,
        3
    ],
    [
        0,
        -1,
        1
    ],
    [
        1,
        0,
        1
    ],
    [
        1,
        0,
        2
    ],
    [
        2,
        -1,
        1
    ],
    [
        1,
        0,
        2
    ],
    [
        1,
        0,
        2
    ],
    [
        2,
        0,
        1
    ],
    [
        1,
        0,
        1
    ],
    [
        2,
        0,
        0
    ],
    [
        1,
        0,
        1
    ],
    [
        1,
        0,
        1
    ],
    [
        3,
        0,
        1
    ],
    [
        0,
        -1,
        1
    ],
    [
        1,
        0,
        1
    ],
    [
        2,
        0,
        3
    ],
    [
        2,
        0,
        1
    ],
    [
        2,
        0,
        1
    ],
    [
        3,
        -1,
        1
    ],
    [
        1,
        0,
        1
    ],
    [
        1,
        0,
        1
    ],
    [
        2,
        0,
        1
    ],
    [
        2,
        0,
        1
    ],
    [
        2,
        -1,
        1
    ],
    [
        1,
        0,
        1
    ],
    [
        1,
        0,
        1
    ],
    [
        1,
        0,
        1
    ],
    [
        2,
        -1,
        1
    ],
    [
        1,
        0,
        0
    ],
    [
        1,
        0,
        1
    ],
    [
        1,
        0,
        1
    ],
    [
        1,
        0,
        3
    ],
    [
        1,
        0,
        1
    ],
    [
        2,
        0,
        1
    ],
    [
        1,
        0,
        1
    ],
    [
        1,
        0,
        1
    ],
    [
        1,
        0,
        2
    ],
    [
        1,
        0,
        0
    ],
    [
        1,
        0,
        1
    ],
    [
        1,
        0,
        3
    ],
    [
        1,
        0,
        2
    ],
    [
        1,
        0,
        2
    ],
    [
        1,
        0,
        1
    ],
    [
        0,
        0,
        2
    ],
    [
        1,
        0,
        2
    ],
    [
        1,
        0,
        4
    ],
    [
        0,
        0,
        7
    ],
    [
        1,
        0,
        40
    ],
    [
        1,
        0,
        9
    ],
    [
        1,
        0,
        9
    ],
    [
        0,
        -1,
        4
    ],
    [
        1,
        0,
        3
    ],
    [
        1,
        0,
        7
    ],
    [
        1,
        0,
        1
    ],
    [
        0,
        -1,
        1
    ],
    [
        1,
        0,
        2
    ],
    [
        1,
        0,
        4
    ],
    [
        1,
        0,
        3
    ],
    [
        1,
        0,
        3
    ],
    [
        0,
        0,
        4
    ],
    [
        1,
        0,
        6
    ],
    [
        1,
        0,
        38
    ],
    [
        1,
        0,
        9
    ],
    [
        1,
        0,
        5
    ],
    [
        1,
        0,
        7
    ],
    [
        1,
        0,
        4
    ],
    [
        1,
        0,
        4
    ],
    [
        1,
        0,
        3
    ],
    [
        1,
        0,
        5
    ],
    [
        1,
        0,
        5
    ],
    [
        0,
        0,
        1
    ],
    [
        1,
        0,
        4
    ],
    [
        1,
        0,
        2
    ],
    [
        2,
        0,
        4
    ],
    [
        1,
        0,
        3
    ],
    [
        1,
        0,
        3
    ],
    [
        1,
        0,
        3
    ],
    [
        1,
        0,
        2
    ],
    [
        1,
        0,
        6
    ],
    [
        1,
        0,
        3
    ],
    [
        0,
        0,
        9
    ],
    [
        1,
        0,
        9
    ],
    [
        1,
        0,
        5
    ],
    [
        1,
        0,
        4
    ],
    [
        1,
        0,
        4
    ],
    [
        1,
        0,
        3
    ],
    [
        1,
        0,
        2
    ],
    [
        1,
        0,
        3
    ],
    [
        1,
        0,
        2
    ],
    [
        1,
        0,
        1
    ],
    [
        1,
        0,
        2
    ],
    [
        0,
        0,
        1
    ],
    [
        1,
        0,
        2
    ],
    [
        1,
        1,
        1
    ],
    [
        1,
        0,
        1
    ],
    [
        1,
        0,
        2
    ],
    [
        1,
        0,
        0
    ],
    [
        1,
        0,
        2
    ],
    [
        2,
        0,
        0
    ],
    [
        1,
        0,
        3
    ],
    [
        1,
        0,
        1
    ],
    [
        0,
        0,
        1
    ],
    [
        1,
        0,
        1
    ],
    [
        1,
        0,
        4
    ],
    [
        1,
        0,
        3
    ],
    [
        2,
        0,
        1
    ],
    [
        1,
        0,
        1
    ],
    [
        1,
        0,
        1
    ],
    [
        1,
        0,
        2
    ],
    [
        1,
        0,
        3
    ],
    [
        0,
        0,
        6
    ],
    [
        1,
        0,
        2
    ],
    [
        1,
        0,
        16
    ],
    [
        1,
        0,
        1153
    ]
]
window = {}
var window = {}

window['Array'] = Array

window.navigator = {}
window.navigator.cookieEnabled = true
window.location = {}
window.location.href = ""
window.getComputedStyle = function () {
    return {}
}
window.matchMedia = function (x) {
    return {media: x, matches: true}
}
var document = {}
document.documentElement = {}
document.charset = "UTF-8"
window.innerWidth = 1920
window.innerHeight = 937
document.documentElement.clientWidth = 1903
document.documentElement.clientHeight = 937
document.body = {}
document.body.clientWidth = 1903
document.body.clientHeight = 1889
document.body = {}
document.body.clientWidth = 476
document.body.clientHeight = 137
document.createElement = function () {
    return []
}
navigator = {}
navigator.userAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
screen = {
    availHeight: 1040,
    availLeft: 0,
    availTop: 0,
    availWidth: 1920,
    colorDepth: 24,
    height: 1080,
    left: 0,
    mozOrientation: "landscape-primary",
    onmozorientationchange: null,
    pixelDepth: 24,
    top: 0,
    width: 1920,
    orientation: {angle: 0, type: "landscape-primary"}
}
window.screen = screen
document.createElement = function (x) {
    return []
}
document.cookie = "TDC_itoken=1117279312%3A1587446300"


var _0x508a9d = {
    "ft": "qf_7P_n_H",
    "coordinate": [10, 63.99147415161133, 0.5],
    "clientType": "2",
    "trycnt": 5,
    "refreshcnt": 0,
    "slideValue": [[75, 287, 37], [1, 0, 4], [1, 0, 6], [1, 0, 3], [1, 0, 3], [1, 0, 6], [1, 0, 3], [1, 0, 3], [2, 0, 1], [1, 0, 5], [1, 0, 1], [2, 0, 1], [1, 0, 2], [1, 0, 2], [0, 0, 1], [2, 0, 0], [1, 0, 4], [1, 0, 1], [2, 1, 4], [2, 0, 2], [1, 1, 1], [1, 0, 1], [2, 0, 5], [0, 1, 4], [4, 0, 2], [3, 0, 1], [5, 1, 1], [0, 1, 1], [2, 0, 0], [3, 0, 2], [0, 0, 2], [3, 0, 0], [2, 0, 3], [1, 0, 0], [2, 1, 1], [1, 0, 3], [1, 0, 2], [1, 0, 1], [3, 0, 1], [1, 0, 1], [1, 0, 0], [2, 1, 1], [1, 0, 2], [2, 0, 1], [1, 0, 1], [2, 0, 2], [1, 0, 4], [1, 0, 2], [1, 1, 1], [2, 0, 1], [2, 0, 2], [0, 0, 1], [1, 0, 1], [1, 0, 2], [1, 0, 3], [2, 0, 8], [2, 0, 1], [1, 0, 2], [1, 0, 4], [1, 0, 7], [0, 0, 3], [1, 0, 6], [1, 0, 15], [0, 0, 9], [1, 0, 3], [1, 0, 2], [0, -1, 2], [1, 0, 3], [0, -1, 2], [2, 0, 3], [1, 0, 6], [1, 0, 1], [1, 0, 4], [0, 0, 3], [1, 0, 1], [2, 0, 4], [1, 0, 4], [1, 0, 2], [1, 0, 2], [1, 0, 1], [2, -1, 4], [1, 0, 3], [0, 0, 2], [2, -1, 3], [1, 0, 3], [1, 0, 3], [1, 0, 0], [1, 0, 2], [2, 0, 4], [1, 0, 21], [1, 0, 1], [4, 0, 2], [1, 0, 1], [1, 0, 2], [1, 0, 6], [1, 0, 1], [1, 0, 2], [1, 0, 2], [0, 0, 4], [1, 0, 2], [1, 0, 1], [1, 0, 8], [1, 0, 2], [2, 0, 1], [1, 0, 1], [1, 0, 3], [2, 0, 3], [0, 0, 87], [1, 0, 10], [0, 1, 6], [1, 0, 1], [1, 0, 2], [1, 0, 3], [0, 1, 2], [1, 0, 2], [1, 0, 2], [1, 0, 1], [1, 0, 2], [1, 0, 4], [1, 1, 1], [1, 0, 1], [1, 0, 1], [1, 0, 2], [1, 0, 1], [1, 0, 3], [1, 0, 1], [1, 0, 2], [0, 1, 2], [1, 0, 1], [1, 0, 1], [0, 0, 16], [1, 0, 1], [2, 0, 1], [2, 0, 72], [1, 0, 20], [1, 0, 24], [1, 0, 10], [1, 0, 5], [1, 0, 1], [0, 0, 4], [1, 0, 1], [1, 0, 5], [1, 0, 1], [1, -1, 1], [2, 0, 5], [1, 0, 1], [1, 0, 2], [1, 0, 0], [1, 0, 2], [0, 0, 1], [2, 0, 2], [1, 0, 2], [2, 0, 3], [1, 0, 3], [1, 0, 1], [2, 0, 2], [2, 0, 1], [2, 0, 2], [1, 0, 2], [1, 0, 2], [1, 0, 2], [1, 0, 4], [1, 0, 1], [0, -1, 22], [-1, 0, 40], [-1, 0, 430], [-1, 0, 15], [-1, 0, 16], [0, 1, 287], [0, 0, 95]],
    "dragobj": 0
}

function setData(data, _0x1d5777) {

    for (var item in data) {
        _0x508a9d[item] = data[item];
    }
    // if (_0x50ff9a[_0xc7a8('0x21')][_0xc7a8('0x140')](data)) {
    //     _0x508a9d[data] = _0x1d5777;
    // }

}

var dict = [
    "parse",
    "mouseclick",
    "keyvalue",
    "user_Agent",
    "resolutionx",
    "resolutiony",
    "url",
    "refer",
    "begintime",
    "endtime",
    "platform",
    "flash",
    "pluginNum",
    "ptcz",
    "prototype",
    "call",
    "[object ",
    "Object",
    "Array",
    "isArray",
    "Function",
    "length",
    "forEach",
    "hasOwnProperty",
    "map",
    "currentStyle",
    "defaultView",
    "style",
    "userAgent",
    "documentElement",
    "doScroll",
    "add",
    "DOMContentLoaded",
    "type",
    "CSS",
    "each",
    "mapArray",
    "DOMReady",
    "cutUrl",
    "referrer",
    "addEventListener",
    "attachEvent",
    "removeEventListener",
    "detachEvent",
    "remove",
    "lib",
    "mixIn",
    "init",
    "apply",
    "extend",
    "toString",
    "words",
    "sigBytes",
    "clamp",
    "push",
    "ceil",
    "slice",
    "Hex",
    "substr",
    "fromCharCode",
    "join",
    "charCodeAt",
    "Utf8",
    "BufferedBlockAlgorithm",
    "_data",
    "_nDataBytes",
    "string",
    "blockSize",
    "max",
    "_minBufferSize",
    "min",
    "_doProcessBlock",
    "clone",
    "cfg",
    "reset",
    "_doReset",
    "_append",
    "_doFinalize",
    "HMAC",
    "finalize",
    "WordArray",
    "enc",
    "Base64",
    "_map",
    "charAt",
    "indexOf",
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",
    "Hasher",
    "algo",
    "abs",
    "sin",
    "MD5",
    "_hash",
    "floor",
    "_process",
    "HmacMD5",
    "_createHmacHelper",
    "Base",
    "EvpKDF",
    "hasher",
    "create",
    "keySize",
    "iterations",
    "update",
    "concat",
    "compute",
    "Cipher",
    "_ENC_XFORM_MODE",
    "_key",
    "decrypt",
    "mode",
    "_iv",
    "_prevBlock",
    "BlockCipherMode",
    "Encryptor",
    "_cipher",
    "encryptBlock",
    "decryptBlock",
    "CBC",
    "Pkcs7",
    "BlockCipher",
    "_xformMode",
    "createDecryptor",
    "_mode",
    "processBlock",
    "padding",
    "pad",
    "unpad",
    "formatter",
    "stringify",
    "format",
    "ciphertext",
    "salt",
    "SerializableCipher",
    "createEncryptor",
    "_parse",
    "kdf",
    "OpenSSL",
    "random",
    "PasswordBasedCipher",
    "ivSize",
    "encrypt",
    "execute",
    "key",
    "_nRounds",
    "_keySchedule",
    "_doCryptBlock",
    "_invKeySchedule",
    "AES",
    "object",
    "use strict",
    "valueOf",
    "toJSON",
    "getUTCFullYear",
    "getUTCMonth",
    "getUTCDate",
    "getUTCHours",
    "getUTCMinutes",
    "lastIndex",
    "test",
    "replace",
    "0000",
    "number",
    "null",
    "boolean",
    "[object Array]",
    "function",
    "JSON.parse",
    "mozRTCPeerConnection",
    "webkitRTCPeerConnection",
    "stun:stun.services.mozilla.com",
    "exec",
    "onicecandidate",
    "candidate",
    "localDescription",
    "sdp",
    "split",
    "a=candidate:",
    "get",
    "match",
    "out",
    "stack",
    "phantomjs",
    "callPhantom",
    "_phantom",
    "appVersion",
    "fxdriver_id",
    "__fxdriver_unwrapped",
    "domAutomation",
    "ubot",
    "awesomium",
    "rhinoException",
    "undefined",
    "substring",
    "[CODE_VERIFY]",
    "target error - target and name are both required",
    "target error - target itself must be window object",
    "target error - target name must be string type",
    "target",
    "name",
    "send",
    "postMessage",
    "navigator",
    "target callback function is not defined",
    "listenFunc",
    "initListen",
    "addTarget",
    "targets",
    "data",
    "message",
    "onmessage",
    "listen",
    "clear",
    "timer",
    "count",
    "interval",
    "start",
    "stop",
    "innerHeight",
    "clientHeight",
    "body",
    "isIE",
    "monospace",
    "getElementsByTagName",
    "createElement",
    "span",
    "fontSize",
    "72px",
    "innerHTML",
    "fontFamily",
    "appendChild",
    "offsetWidth",
    "offsetHeight",
    "removeChild",
    "detect",
    "Symbol;Arial;Courier New;Times New Roman;Georgia;Trebuchet MS;Verdana;Impact;Comic Sans MS;Webdings;Tahoma;Microsoft Sans Serif;Wingdings;Arial Black;Lucida Console;Marlett;Lucida Sans Unicode;Courier;Franklin Gothic Medium;Palatino Linotype",
    "getRegularPluginsString",
    "getIEPluginsString",
    "ShockwaveFlash.ShockwaveFlash",
    "AcroPDF.PDF",
    "PDF.PdfCtrl",
    "QuickTime.QuickTime",
    "rmocx.RealPlayer G2 Control",
    "rmocx.RealPlayer G2 Control.1",
    "RealPlayer.RealPlayer(tm) ActiveX Control (32-bit)",
    "RealVideo.RealVideo(tm) ActiveX Control (32-bit)",
    "RealPlayer",
    "SWCtl.SWCtl",
    "AgControl.AgControl",
    "width",
    "availHeight",
    "colorDepth",
    "deviceXDPI",
    "logicalXDPI",
    "fontSmoothingEnabled",
    "plugins",
    "description",
    "$version",
    "characterSet",
    "languages",
    "localStorage",
    "indexedDB",
    "getFullYear",
    "toGMTString",
    "collectFonts",
    "getCharSet",
    "collectScreen",
    "reportError",
    "getErrors",
    "querySelectorAll",
    "input",
    "blur",
    "cIPT",
    "; expires=",
    "; path=",
    "; domain=",
    "; secure",
    "cookie",
    "set",
    "unset",
    "getTime",
    "atob",
    "btoa",
    "'btoa' failed: The string to be encoded contains characters outside of the Latin1 range.",
    "currentScript",
    "script",
    "src",
    "https://bsp.qcloud.qq.com/v2/index.php",
    "height",
    "winSize",
    "index",
    "tokenid",
    "btokenid",
    "tokents",
    "ips",
    "cookieEnabled",
    "timezone",
    "mousemove",
    "keyUpCnt",
    "keyUpValue",
    "mouseUpCnt",
    "mouseDownValue",
    "mouseDownCnt",
    "bSimutor",
    "focusBlur",
    "getFlashVersion",
    "charSet",
    "resizeCnt",
    "errors",
    "screenInfo",
    "elapsed",
    "0123456789abcdef",
    "?Action=WebInfo&siteKey=",
    "&content=",
    "offsetLeft",
    "offsetParent",
    "toLowerCase",
    "offsetTop",
    "tagName",
    "isObject",
    "isString",
    "wheelDelta",
    "detail",
    "load",
    "event",
    "className",
    "getData",
    "touchend",
    "changedTouches",
    "clientX",
    "clientY",
    "touchstart",
    "touchmove",
    "round",
    "toFixed",
    "pageX",
    "pageY",
    "scrollLeft",
    "clientLeft",
    "scrollTop",
    "clientTop",
    "touches",
    "alpha",
    "beta",
    "gamma",
    "Win32",
    "Mac68K",
    "MacPPC",
    "MacIntel",
    "X11",
    "Unix",
    "Linux",
    "android",
    "Android",
    "like mac os x",
    "IOS",
    "Windows NT 5.0",
    "Windows NT 5.1",
    "Windows XP",
    "WinXP",
    "Windows NT 5.2",
    "Windows 2003",
    "Win2003",
    "Windows NT 6.0",
    "Windows Vista",
    "WinVista",
    "Windows NT 6.1",
    "Windows 7",
    "other",
    "msie",
    "chrome",
    "div",
    "ontuchstart",
    "GetVariable",
    "Shockwave Flash",
    "iframes",
    "parent_dc",
    "parent",
    "child",
    "0px",
    "hidden",
    "iframe",
    "TDC_bfp",
    "ontouchstart",
    "mouseup",
    "mousedown",
    "keyup",
    "click",
    "mousewheel",
    "DOMMouseScroll",
    "setConfig",
    "HandShake",
    "contentWindow",
    "TDC",
    "Messenger"
]
var _0x3a2110 = "https://captcha.guard.qcloud.com/cap_union_new_show"
var _0x277af8 = "https://accounts.douban.com/passport/login"
var time = new Date().getTime();

function _0xc7a8(index) {
    index = index - 0x0
    return dict[index]
}

var _0x3e7c55 = {
    w: function _0x42536a() {
        return window['innerWidth'] || _0x1de329[_0xc7a8('0x1d')]['\x63\x6c\x69\x65\x6e\x74\x57\x69\x64\x74\x68'] || _0x1de329['\x62\x6f\x64\x79']['\x63\x6c\x69\x65\x6e\x74\x57\x69\x64\x74\x68'];
    },
    h: function _0x2d748a() {
        return window[_0xc7a8('0xda')] || _0x1de329[_0xc7a8('0x1d')][_0xc7a8('0xdb')] || _0x1de329[_0xc7a8('0xdc')][_0xc7a8('0xdb')];
    }

}


var _0x1b0e23 = {
    "mouseclick": [
        {
            "t": 813,
            "x": 263,
            "y": 294
        }
    ],
    "keyvalue": [],
    "user_Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 Edg/81.0.416.72",
    "resolutionx": 1920,
    "resolutiony": 1080,
    "winSize": [
        360,
        360
    ],
    "url": "https://captcha.guard.qcloud.com/cap_union_new_show",
    "refer": "https://accounts.douban.com/passport/login",
    "begintime": 1589766509,
    "endtime": 1589767322,
    "platform": 1,
    "os": "other",
    "keyboards": 0,
    "flash": 0,
    "pluginNum": 3,
    "index": 5,
    "ptcz": "",
    "tokenid": 3848168659,
    "a": 3848168659,
    "btokenid": null,
    "tokents": 1575614801,
    "ips": {},
    "colorDepth": 24,
    "cookieEnabled": true,
    "timezone": 8,
    "wDelta": 0,
    "mousemove": [
        [
            283,
            300,
            661216
        ],
        [
            -1,
            0,
            5
        ],
        [
            -1,
            0,
            2
        ],
        [
            -1,
            0,
            5
        ],
        [
            0,
            0,
            5
        ],
        [
            -1,
            0,
            2
        ],
        [
            -1,
            0,
            2
        ],
        [
            -1,
            0,
            3
        ],
        [
            0,
            1,
            1
        ],
        [
            -1,
            0,
            2
        ],
        [
            -1,
            0,
            2
        ],
        [
            -1,
            0,
            1
        ],
        [
            -1,
            1,
            3
        ],
        [
            -1,
            0,
            2
        ],
        [
            0,
            1,
            1
        ],
        [
            -1,
            0,
            1
        ],
        [
            -1,
            0,
            1
        ],
        [
            0,
            0,
            3
        ],
        [
            -1,
            1,
            3
        ],
        [
            -1,
            0,
            2
        ],
        [
            -1,
            0,
            1
        ],
        [
            -1,
            0,
            18
        ],
        [
            -1,
            0,
            0
        ],
        [
            -4,
            1,
            1
        ],
        [
            0,
            1,
            2
        ],
        [
            -1,
            0,
            3
        ],
        [
            0,
            1,
            2
        ],
        [
            0,
            0,
            3
        ],
        [
            -1,
            0,
            1
        ],
        [
            -1,
            0,
            5
        ],
        [
            -1,
            0,
            3
        ],
        [
            -1,
            0,
            3
        ],
        [
            -1,
            0,
            1
        ],
        [
            -1,
            0,
            3
        ],
        [
            -1,
            0,
            3
        ],
        [
            0,
            1,
            1
        ],
        [
            -1,
            0,
            1
        ],
        [
            -1,
            0,
            1
        ],
        [
            -1,
            0,
            3
        ],
        [
            -1,
            0,
            1
        ],
        [
            0,
            0,
            2
        ],
        [
            -1,
            0,
            2
        ],
        [
            -1,
            0,
            2
        ],
        [
            -1,
            0,
            2
        ],
        [
            -1,
            0,
            3
        ],
        [
            -1,
            0,
            0
        ],
        [
            -1,
            0,
            2
        ],
        [
            0,
            1,
            1
        ],
        [
            -1,
            0,
            1
        ],
        [
            -1,
            0,
            2
        ],
        [
            -1,
            0,
            1
        ],
        [
            -1,
            0,
            2
        ],
        [
            0,
            0,
            2
        ],
        [
            -63,
            4,
            1020
        ],
        [
            0,
            -1,
            0
        ],
        [
            -1,
            0,
            1
        ],
        [
            0,
            -1,
            1
        ],
        [
            -1,
            -1,
            2
        ],
        [
            0,
            0,
            1
        ],
        [
            -1,
            0,
            1
        ],
        [
            0,
            -1,
            1
        ],
        [
            0,
            -1,
            1
        ],
        [
            -1,
            -1,
            2
        ],
        [
            0,
            -1,
            1
        ],
        [
            0,
            -1,
            2
        ],
        [
            -1,
            -1,
            2
        ],
        [
            0,
            -1,
            2
        ],
        [
            0,
            -1,
            3
        ],
        [
            -1,
            -1,
            1
        ],
        [
            0,
            -1,
            2
        ],
        [
            0,
            0,
            2
        ],
        [
            0,
            -1,
            1
        ],
        [
            0,
            -1,
            5
        ],
        [
            -1,
            0,
            0
        ],
        [
            0,
            -1,
            2
        ],
        [
            0,
            -1,
            8
        ],
        [
            0,
            -1,
            3
        ],
        [
            0,
            -1,
            30
        ],
        [
            0,
            -1,
            10
        ],
        [
            0,
            -1,
            7
        ],
        [
            0,
            -1,
            4
        ],
        [
            0,
            -1,
            4
        ],
        [
            0,
            0,
            6
        ],
        [
            0,
            -1,
            5
        ],
        [
            0,
            -1,
            1
        ],
        [
            0,
            -1,
            5
        ],
        [
            0,
            -1,
            7
        ],
        [
            0,
            -1,
            6
        ],
        [
            0,
            -1,
            4
        ],
        [
            0,
            -1,
            195
        ],
        [
            0,
            -1,
            7
        ],
        [
            0,
            -1,
            11
        ],
        [
            0,
            -1,
            18
        ],
        [
            0,
            0,
            1
        ],
        [
            1,
            0,
            2
        ],
        [
            0,
            0,
            2
        ],
        [
            0,
            -1,
            3
        ],
        [
            1,
            0,
            0
        ],
        [
            1,
            -1,
            2
        ],
        [
            1,
            0,
            1
        ],
        [
            0,
            -1,
            1
        ],
        [
            1,
            0,
            1
        ],
        [
            1,
            0,
            1
        ],
        [
            1,
            -2,
            1
        ],
        [
            2,
            0,
            1
        ],
        [
            1,
            0,
            1
        ],
        [
            1,
            -2,
            1
        ],
        [
            2,
            -1,
            1
        ],
        [
            2,
            0,
            1
        ],
        [
            1,
            -1,
            1
        ],
        [
            3,
            -1,
            1
        ],
        [
            2,
            -1,
            1
        ],
        [
            3,
            -2,
            1
        ],
        [
            3,
            -1,
            1
        ],
        [
            3,
            -1,
            1
        ],
        [
            3,
            -3,
            1
        ],
        [
            3,
            -1,
            1
        ],
        [
            4,
            -1,
            1
        ],
        [
            4,
            -3,
            1
        ],
        [
            6,
            -2,
            1
        ],
        [
            4,
            -3,
            1
        ],
        [
            6,
            -3,
            1
        ],
        [
            4,
            -2,
            1
        ],
        [
            5,
            -1,
            1
        ],
        [
            6,
            -5,
            1
        ],
        [
            5,
            -3,
            2
        ],
        [
            7,
            -3,
            1
        ],
        [
            7,
            -4,
            2
        ],
        [
            7,
            -3,
            1
        ],
        [
            12,
            -8,
            0
        ],
        [
            9,
            -5,
            1
        ],
        [
            9,
            -4,
            1
        ],
        [
            6,
            -4,
            1
        ],
        [
            8,
            -6,
            1
        ],
        [
            8,
            -3,
            1
        ],
        [
            9,
            -7,
            1
        ],
        [
            9,
            -3,
            1
        ],
        [
            9,
            -6,
            0
        ],
        [
            7,
            -4,
            2
        ],
        [
            -305,
            101,
            7963
        ],
        [
            1,
            0,
            3
        ],
        [
            1,
            0,
            7
        ],
        [
            2,
            0,
            3
        ],
        [
            1,
            0,
            3
        ],
        [
            1,
            -1,
            2
        ],
        [
            1,
            0,
            1
        ],
        [
            1,
            0,
            1
        ],
        [
            0,
            0,
            3
        ],
        [
            2,
            0,
            2
        ],
        [
            1,
            0,
            1
        ],
        [
            1,
            0,
            1
        ],
        [
            1,
            0,
            1
        ],
        [
            1,
            0,
            1
        ],
        [
            1,
            0,
            1
        ],
        [
            1,
            0,
            1
        ],
        [
            2,
            0,
            1
        ],
        [
            1,
            0,
            1
        ],
        [
            2,
            0,
            1
        ],
        [
            2,
            0,
            2
        ],
        [
            1,
            0,
            1
        ],
        [
            3,
            0,
            0
        ],
        [
            1,
            0,
            2
        ],
        [
            1,
            0,
            3
        ],
        [
            1,
            0,
            0
        ],
        [
            2,
            0,
            1
        ],
        [
            2,
            0,
            1
        ],
        [
            2,
            0,
            0
        ],
        [
            1,
            0,
            1
        ],
        [
            2,
            0,
            1
        ],
        [
            1,
            0,
            1
        ],
        [
            2,
            0,
            1
        ],
        [
            3,
            1,
            1
        ],
        [
            1,
            0,
            1
        ],
        [
            2,
            0,
            1
        ],
        [
            2,
            0,
            1
        ],
        [
            2,
            0,
            1
        ],
        [
            2,
            0,
            1
        ],
        [
            1,
            1,
            1
        ],
        [
            1,
            0,
            1
        ],
        [
            2,
            0,
            1
        ],
        [
            0,
            0,
            1
        ],
        [
            4,
            0,
            1
        ],
        [
            1,
            0,
            1
        ],
        [
            2,
            0,
            1
        ],
        [
            1,
            0,
            0
        ],
        [
            2,
            0,
            1
        ],
        [
            1,
            0,
            1
        ],
        [
            2,
            0,
            3
        ],
        [
            2,
            0,
            0
        ],
        [
            2,
            0,
            1
        ],
        [
            2,
            0,
            1
        ],
        [
            9,
            0,
            10
        ],
        [
            1,
            0,
            1
        ],
        [
            2,
            0,
            0
        ],
        [
            0,
            0,
            1
        ],
        [
            2,
            0,
            2
        ],
        [
            1,
            0,
            2
        ],
        [
            1,
            0,
            0
        ],
        [
            1,
            0,
            2
        ],
        [
            1,
            0,
            0
        ],
        [
            1,
            0,
            2
        ]
    ],
    "keyUpCnt": 0,
    "keyUpValue": [],
    "mouseUpValue": [
        {
            "t": 853,
            "x": 222,
            "y": 292
        }
    ],
    "mouseUpCnt": 1,
    "mouseDownValue": [],
    "mouseDownCnt": 0,
    "orientation": [],
    "bSimutor": 0,
    "focusBlur": {
        "in": [],
        "out": [],
        "t": []
    },
    "fVersion": 0,
    "charSet": "UTF-8",
    "resizeCnt": 0,
    "errors": [],
    "screenInfo": "1920-1080-1050-24-*-*-*",
    "elapsed": 1000,
    "ft": "qf_7P_n_H",
    "coordinate": [
        10,
        63.99147415161133,
        0.5
    ],
    "clientType": "2",
    "trycnt": 5,
    "refreshcnt": 0,
    "slideValue": [
        [
            75,
            287,
            37
        ],
        [
            1,
            0,
            4
        ],
        [
            1,
            0,
            6
        ],
        [
            1,
            0,
            3
        ],
        [
            1,
            0,
            3
        ],
        [
            1,
            0,
            6
        ],
        [
            1,
            0,
            3
        ],
        [
            1,
            0,
            3
        ],
        [
            2,
            0,
            1
        ],
        [
            1,
            0,
            5
        ],
        [
            1,
            0,
            1
        ],
        [
            2,
            0,
            1
        ],
        [
            1,
            0,
            2
        ],
        [
            1,
            0,
            2
        ],
        [
            0,
            0,
            1
        ],
        [
            2,
            0,
            0
        ],
        [
            1,
            0,
            4
        ],
        [
            1,
            0,
            1
        ],
        [
            2,
            1,
            4
        ],
        [
            2,
            0,
            2
        ],
        [
            1,
            1,
            1
        ],
        [
            1,
            0,
            1
        ],
        [
            2,
            0,
            5
        ],
        [
            0,
            1,
            4
        ],
        [
            4,
            0,
            2
        ],
        [
            3,
            0,
            1
        ],
        [
            5,
            1,
            1
        ],
        [
            0,
            1,
            1
        ],
        [
            2,
            0,
            0
        ],
        [
            3,
            0,
            2
        ],
        [
            0,
            0,
            2
        ],
        [
            3,
            0,
            0
        ],
        [
            2,
            0,
            3
        ],
        [
            1,
            0,
            0
        ],
        [
            2,
            1,
            1
        ],
        [
            1,
            0,
            3
        ],
        [
            1,
            0,
            2
        ],
        [
            1,
            0,
            1
        ],
        [
            3,
            0,
            1
        ],
        [
            1,
            0,
            1
        ],
        [
            1,
            0,
            0
        ],
        [
            2,
            1,
            1
        ],
        [
            1,
            0,
            2
        ],
        [
            2,
            0,
            1
        ],
        [
            1,
            0,
            1
        ],
        [
            2,
            0,
            2
        ],
        [
            1,
            0,
            4
        ],
        [
            1,
            0,
            2
        ],
        [
            1,
            1,
            1
        ],
        [
            2,
            0,
            1
        ],
        [
            2,
            0,
            2
        ],
        [
            0,
            0,
            1
        ],
        [
            1,
            0,
            1
        ],
        [
            1,
            0,
            2
        ],
        [
            1,
            0,
            3
        ],
        [
            2,
            0,
            8
        ],
        [
            2,
            0,
            1
        ],
        [
            1,
            0,
            2
        ],
        [
            1,
            0,
            4
        ],
        [
            1,
            0,
            7
        ],
        [
            0,
            0,
            3
        ],
        [
            1,
            0,
            6
        ],
        [
            1,
            0,
            15
        ],
        [
            0,
            0,
            9
        ],
        [
            1,
            0,
            3
        ],
        [
            1,
            0,
            2
        ],
        [
            0,
            -1,
            2
        ],
        [
            1,
            0,
            3
        ],
        [
            0,
            -1,
            2
        ],
        [
            2,
            0,
            3
        ],
        [
            1,
            0,
            6
        ],
        [
            1,
            0,
            1
        ],
        [
            1,
            0,
            4
        ],
        [
            0,
            0,
            3
        ],
        [
            1,
            0,
            1
        ],
        [
            2,
            0,
            4
        ],
        [
            1,
            0,
            4
        ],
        [
            1,
            0,
            2
        ],
        [
            1,
            0,
            2
        ],
        [
            1,
            0,
            1
        ],
        [
            2,
            -1,
            4
        ],
        [
            1,
            0,
            3
        ],
        [
            0,
            0,
            2
        ],
        [
            2,
            -1,
            3
        ],
        [
            1,
            0,
            3
        ],
        [
            1,
            0,
            3
        ],
        [
            1,
            0,
            0
        ],
        [
            1,
            0,
            2
        ],
        [
            2,
            0,
            4
        ],
        [
            1,
            0,
            21
        ],
        [
            1,
            0,
            1
        ],
        [
            4,
            0,
            2
        ],
        [
            1,
            0,
            1
        ],
        [
            1,
            0,
            2
        ],
        [
            1,
            0,
            6
        ],
        [
            1,
            0,
            1
        ],
        [
            1,
            0,
            2
        ],
        [
            1,
            0,
            2
        ],
        [
            0,
            0,
            4
        ],
        [
            1,
            0,
            2
        ],
        [
            1,
            0,
            1
        ],
        [
            1,
            0,
            8
        ],
        [
            1,
            0,
            2
        ],
        [
            2,
            0,
            1
        ],
        [
            1,
            0,
            1
        ],
        [
            1,
            0,
            3
        ],
        [
            2,
            0,
            3
        ],
        [
            0,
            0,
            87
        ],
        [
            1,
            0,
            10
        ],
        [
            0,
            1,
            6
        ],
        [
            1,
            0,
            1
        ],
        [
            1,
            0,
            2
        ],
        [
            1,
            0,
            3
        ],
        [
            0,
            1,
            2
        ],
        [
            1,
            0,
            2
        ],
        [
            1,
            0,
            2
        ],
        [
            1,
            0,
            1
        ],
        [
            1,
            0,
            2
        ],
        [
            1,
            0,
            4
        ],
        [
            1,
            1,
            1
        ],
        [
            1,
            0,
            1
        ],
        [
            1,
            0,
            1
        ],
        [
            1,
            0,
            2
        ],
        [
            1,
            0,
            1
        ],
        [
            1,
            0,
            3
        ],
        [
            1,
            0,
            1
        ],
        [
            1,
            0,
            2
        ],
        [
            0,
            1,
            2
        ],
        [
            1,
            0,
            1
        ],
        [
            1,
            0,
            1
        ],
        [
            0,
            0,
            16
        ],
        [
            1,
            0,
            1
        ],
        [
            2,
            0,
            1
        ],
        [
            2,
            0,
            72
        ],
        [
            1,
            0,
            20
        ],
        [
            1,
            0,
            24
        ],
        [
            1,
            0,
            10
        ],
        [
            1,
            0,
            5
        ],
        [
            1,
            0,
            1
        ],
        [
            0,
            0,
            4
        ],
        [
            1,
            0,
            1
        ],
        [
            1,
            0,
            5
        ],
        [
            1,
            0,
            1
        ],
        [
            1,
            -1,
            1
        ],
        [
            2,
            0,
            5
        ],
        [
            1,
            0,
            1
        ],
        [
            1,
            0,
            2
        ],
        [
            1,
            0,
            0
        ],
        [
            1,
            0,
            2
        ],
        [
            0,
            0,
            1
        ],
        [
            2,
            0,
            2
        ],
        [
            1,
            0,
            2
        ],
        [
            2,
            0,
            3
        ],
        [
            1,
            0,
            3
        ],
        [
            1,
            0,
            1
        ],
        [
            2,
            0,
            2
        ],
        [
            2,
            0,
            1
        ],
        [
            2,
            0,
            2
        ],
        [
            1,
            0,
            2
        ],
        [
            1,
            0,
            2
        ],
        [
            1,
            0,
            2
        ],
        [
            1,
            0,
            4
        ],
        [
            1,
            0,
            1
        ],
        [
            0,
            -1,
            22
        ],
        [
            -1,
            0,
            40
        ],
        [
            -1,
            0,
            430
        ],
        [
            -1,
            0,
            15
        ],
        [
            -1,
            0,
            16
        ],
        [
            0,
            1,
            287
        ],
        [
            0,
            0,
            95
        ]
    ],
    "dragobj": 0
}
var _0x22b065, _0x523a67, _0x487fb1, _0x9b15e8, _0x24b8f7
var _0x3f9b04 = ["mousemove", "mouseclick", "keyvalue", "user_Agent", "resolutionx", "resolutiony", "url", "refer", "begintime", "endtime", "platform", "os", "keyboards", "flash", "pluginNum", "index", "ptcz", "tokenid"]
        var _0x18ea41 = function() {
            _0x57d4a2['\x6c\x65\x6e\x67\x74\x68'] = _0x1b0e23['\x6d\x6f\x75\x73\x65\x63\x6c\x69\x63\x6b'][_0xc7a8('0x15')] = _0x78dab8[_0xc7a8('0x15')] = _0x35bc6d['\x6c\x65\x6e\x67\x74\x68'] = 0x0;
            _0x1b0e23[_0xc7a8('0x2')][_0xc7a8('0x15')] = _0x9bb39d[_0xc7a8('0x15')] = 0x0;
            _0x22b065 = _0x523a67 = _0x487fb1 = _0x9b15e8 = _0x24b8f7 = 0x0;
        };
function getData(_0x826648) {
    // _0x1b0e23[_0xc7a8('0x3')] = navigator[_0xc7a8('0x1c')];
    // _0x1b0e23[_0xc7a8('0x4')] = screen[_0xc7a8('0xf9')];
    // _0x1b0e23[_0xc7a8('0x5')] = screen[_0xc7a8('0x120')];
    // _0x1b0e23[_0xc7a8('0x121')] = [_0x3e7c55['\x77'](), _0x3e7c55['\x68']()];
    // _0x1b0e23[_0xc7a8('0x6')] = _0x3a2110;
    // _0x1b0e23[_0xc7a8('0x7')] = _0x277af8;
    // _0x1b0e23[_0xc7a8('0x8')] = time;
    // _0x1b0e23[_0xc7a8('0x9')] = Math[_0xc7a8('0x5d')](Date[_0xc7a8('0x0')](new Date()) / 0x3e8);
    // _0x1b0e23[_0xc7a8('0xa')] = 1;
    // _0x1b0e23['\x6f\x73'] = "other";
    // _0x1b0e23['\x6b\x65\x79\x62\x6f\x61\x72\x64\x73'] = 0;
    // _0x1b0e23[_0xc7a8('0xb')] = 0;
    // _0x1b0e23[_0xc7a8('0xc')] = 3;
    // _0x1b0e23[_0xc7a8('0x122')] = 6;
    // _0x1b0e23[_0xc7a8('0xd')] = "";
    // _0x1b0e23[_0xc7a8('0x123')] = 3848168659;
    // _0x1b0e23['\x61'] = 3848168;
    // _0x1b0e23[_0xc7a8('0x124')] = null;
    // _0x1b0e23[_0xc7a8('0x125')] = time;
    // _0x1b0e23[_0xc7a8('0x126')] = {};
    // _0x1b0e23['\x63\x6f\x6c\x6f\x72\x44\x65\x70\x74\x68'] = screen['\x63\x6f\x6c\x6f\x72\x44\x65\x70\x74\x68'];
    // _0x1b0e23[_0xc7a8('0x127')] = window[_0xc7a8('0xca')][_0xc7a8('0x127')];
    // // _0x1b0e23[_0xc7a8('0x128')] = _0x31144b['collectTimeZone']();
    // _0x1b0e23[_0xc7a8('0x128')] = 8;
    // _0x1b0e23['wDelta'] = 0;
    // _0x1b0e23[_0xc7a8('0x129')] = arr;
    // _0x1b0e23[_0xc7a8('0x12a')] = 0;
    // _0x1b0e23[_0xc7a8('0x12b')] = [];
    // _0x1b0e23['mouseUpValue'] = [{t: 853, y: 292, x: 222}];
    // _0x1b0e23["mouseUpCnt"] = 1;
    // _0x1b0e23[_0xc7a8('0x12d')] = [];
    // _0x1b0e23[_0xc7a8('0x12e')] = _0x487fb1;
    // _0x1b0e23['\x6f\x72\x69\x65\x6e\x74\x61\x74\x69\x6f\x6e'] = _0x376fa7;
    // _0x1b0e23[_0xc7a8('0x12f')] = _0xab9903();
    // _0x1b0e23[_0xc7a8('0x130')] = _0x143180[_0xc7a8('0xb2')]();
    // _0x1b0e23['\x66\x56\x65\x72\x73\x69\x6f\x6e'] = _0x31144b[_0xc7a8('0x131')]();
    // _0x1b0e23[_0xc7a8('0x132')] = _0x31144b['\x67\x65\x74\x43\x68\x61\x72\x53\x65\x74']();
    // _0x1b0e23[_0xc7a8('0x133')] = _0x236e68;
    // _0x1b0e23[_0xc7a8('0x134')] = _0x31144b[_0xc7a8('0x10c')]();
    // _0x1b0e23[_0xc7a8('0x135')] = _0x31144b[_0xc7a8('0x10a')]();
    // _0x1b0e23[_0xc7a8('0x136')] = _0x1860d8;
    var _0x1b0e23 = {
        "mouseclick": [
            {
                "t": 813,
                "x": 263,
                "y": 294
            }
        ],
        "keyvalue": [],
        "user_Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 Edg/81.0.416.72",
        "resolutionx": 1920,
        "resolutiony": 1080,
        "winSize": [
            360,
            360
        ],
        "url": "https://captcha.guard.qcloud.com/cap_union_new_show",
        "refer": "https://accounts.douban.com/passport/login",
        "begintime": 1589766509,
        "endtime": 1589770578,
        "platform": 1,
        "os": "other",
        "keyboards": 0,
        "flash": 0,
        "pluginNum": 3,
        "index": 7,
        "ptcz": "",
        "tokenid": 3848168659,
        "a": 3848168659,
        "btokenid": null,
        "tokents": 1575614801,
        "ips": {},
        "colorDepth": 24,
        "cookieEnabled": true,
        "timezone": 8,
        "wDelta": 0,
        "mousemove": [
            [
                50,
                283,
                842790
            ],
            [
                1,
                0,
                3
            ],
            [
                1,
                0,
                4
            ],
            [
                1,
                0,
                4
            ],
            [
                1,
                0,
                4
            ],
            [
                1,
                0,
                0
            ],
            [
                1,
                0,
                4
            ],
            [
                1,
                0,
                2
            ],
            [
                1,
                0,
                2
            ],
            [
                1,
                0,
                0
            ],
            [
                0,
                0,
                1
            ],
            [
                2,
                0,
                2
            ],
            [
                1,
                0,
                2
            ],
            [
                1,
                0,
                1
            ],
            [
                1,
                0,
                2
            ],
            [
                1,
                0,
                1
            ],
            [
                2,
                0,
                0
            ],
            [
                1,
                0,
                1
            ],
            [
                2,
                0,
                1
            ],
            [
                0,
                0,
                2
            ],
            [
                2,
                0,
                1
            ],
            [
                2,
                0,
                1
            ],
            [
                1,
                0,
                1
            ],
            [
                2,
                0,
                1
            ],
            [
                2,
                1,
                1
            ],
            [
                1,
                0,
                1
            ],
            [
                3,
                0,
                1
            ],
            [
                2,
                0,
                1
            ],
            [
                2,
                0,
                1
            ],
            [
                2,
                0,
                1
            ],
            [
                2,
                0,
                0
            ],
            [
                2,
                0,
                1
            ],
            [
                2,
                0,
                1
            ],
            [
                2,
                0,
                2
            ],
            [
                3,
                0,
                0
            ],
            [
                2,
                0,
                1
            ],
            [
                2,
                0,
                1
            ],
            [
                3,
                0,
                2
            ],
            [
                2,
                0,
                1
            ],
            [
                2,
                0,
                0
            ],
            [
                2,
                0,
                1
            ],
            [
                2,
                0,
                1
            ],
            [
                3,
                0,
                1
            ],
            [
                1,
                0,
                1
            ],
            [
                2,
                -1,
                1
            ],
            [
                3,
                0,
                1
            ],
            [
                3,
                0,
                1
            ],
            [
                2,
                0,
                1
            ],
            [
                1,
                0,
                1
            ],
            [
                4,
                0,
                3
            ],
            [
                2,
                0,
                1
            ],
            [
                2,
                0,
                0
            ],
            [
                2,
                0,
                1
            ],
            [
                1,
                0,
                2
            ],
            [
                2,
                0,
                1
            ],
            [
                2,
                0,
                1
            ],
            [
                1,
                0,
                0
            ],
            [
                3,
                0,
                1
            ],
            [
                1,
                0,
                1
            ],
            [
                0,
                0,
                1
            ],
            [
                2,
                0,
                1
            ],
            [
                2,
                0,
                1
            ],
            [
                1,
                0,
                1
            ],
            [
                1,
                0,
                1
            ],
            [
                1,
                0,
                1
            ],
            [
                2,
                0,
                1
            ],
            [
                1,
                0,
                1
            ],
            [
                0,
                0,
                1
            ],
            [
                1,
                0,
                1
            ],
            [
                1,
                0,
                2
            ],
            [
                1,
                0,
                1
            ],
            [
                2,
                0,
                0
            ],
            [
                1,
                0,
                2
            ],
            [
                1,
                0,
                1
            ],
            [
                1,
                0,
                1
            ],
            [
                2,
                0,
                2
            ],
            [
                1,
                0,
                1
            ],
            [
                1,
                0,
                2
            ],
            [
                1,
                0,
                2
            ],
            [
                1,
                0,
                2
            ],
            [
                1,
                0,
                1
            ],
            [
                1,
                0,
                3
            ],
            [
                1,
                0,
                2
            ],
            [
                1,
                0,
                2
            ],
            [
                1,
                0,
                2
            ],
            [
                1,
                1,
                4
            ],
            [
                0,
                0,
                106
            ],
            [
                -1,
                0,
                46
            ],
            [
                -1,
                0,
                4
            ],
            [
                -1,
                0,
                10
            ],
            [
                -1,
                0,
                11
            ],
            [
                -1,
                0,
                6
            ],
            [
                -1,
                0,
                5
            ],
            [
                -1,
                0,
                11
            ],
            [
                -1,
                0,
                19
            ],
            [
                0,
                0,
                405
            ],
            [
                0,
                -1,
                23
            ],
            [
                0,
                -1,
                6
            ],
            [
                0,
                -1,
                6
            ],
            [
                0,
                -1,
                5
            ],
            [
                0,
                0,
                3
            ],
            [
                1,
                0,
                1
            ],
            [
                0,
                -1,
                2
            ],
            [
                0,
                -1,
                4
            ],
            [
                1,
                0,
                5
            ],
            [
                0,
                -2,
                2
            ],
            [
                1,
                0,
                1
            ],
            [
                0,
                -1,
                6
            ],
            [
                1,
                0,
                3
            ],
            [
                0,
                -1,
                2
            ],
            [
                0,
                -1,
                2
            ],
            [
                1,
                0,
                1
            ],
            [
                0,
                -1,
                1
            ],
            [
                1,
                0,
                3
            ],
            [
                1,
                -1,
                2
            ],
            [
                1,
                -1,
                3
            ],
            [
                0,
                0,
                2
            ],
            [
                0,
                0,
                1
            ],
            [
                1,
                -1,
                1
            ],
            [
                1,
                0,
                1
            ],
            [
                1,
                -1,
                2
            ],
            [
                1,
                0,
                1
            ],
            [
                1,
                0,
                1
            ],
            [
                0,
                -1,
                1
            ],
            [
                1,
                -1,
                2
            ],
            [
                2,
                0,
                0
            ],
            [
                0,
                -1,
                1
            ],
            [
                2,
                0,
                1
            ],
            [
                0,
                0,
                1
            ],
            [
                1,
                -2,
                1
            ],
            [
                2,
                -1,
                1
            ],
            [
                1,
                0,
                1
            ],
            [
                1,
                -1,
                1
            ],
            [
                2,
                -1,
                1
            ],
            [
                1,
                0,
                2
            ],
            [
                2,
                -1,
                1
            ],
            [
                1,
                -1,
                0
            ],
            [
                1,
                -2,
                1
            ],
            [
                2,
                -1,
                1
            ],
            [
                3,
                -1,
                2
            ],
            [
                2,
                -1,
                0
            ],
            [
                1,
                -2,
                1
            ],
            [
                2,
                -1,
                1
            ],
            [
                2,
                -1,
                1
            ],
            [
                2,
                -1,
                2
            ],
            [
                2,
                -2,
                0
            ],
            [
                2,
                -1,
                1
            ],
            [
                3,
                -2,
                2
            ],
            [
                2,
                -2,
                1
            ],
            [
                3,
                -1,
                0
            ],
            [
                1,
                -1,
                1
            ],
            [
                3,
                -1,
                1
            ],
            [
                3,
                -2,
                1
            ],
            [
                2,
                -2,
                1
            ],
            [
                2,
                -1,
                1
            ],
            [
                2,
                -1,
                1
            ],
            [
                4,
                -2,
                1
            ],
            [
                2,
                -1,
                1
            ],
            [
                2,
                -1,
                1
            ],
            [
                2,
                -1,
                1
            ],
            [
                3,
                -2,
                1
            ],
            [
                3,
                -1,
                1
            ],
            [
                3,
                -3,
                1
            ],
            [
                2,
                -1,
                1
            ],
            [
                2,
                -1,
                2
            ],
            [
                4,
                -1,
                0
            ],
            [
                1,
                0,
                1
            ],
            [
                3,
                -3,
                1
            ],
            [
                2,
                -1,
                1
            ],
            [
                4,
                -1,
                1
            ],
            [
                2,
                -2,
                1
            ],
            [
                1,
                -1,
                1
            ],
            [
                3,
                0,
                1
            ],
            [
                2,
                -2,
                2
            ],
            [
                3,
                -1,
                1
            ],
            [
                1,
                -2,
                0
            ],
            [
                2,
                -1,
                1
            ],
            [
                3,
                -1,
                1
            ],
            [
                3,
                -1,
                1
            ],
            [
                2,
                -2,
                15
            ],
            [
                2,
                0,
                0
            ],
            [
                13,
                -7,
                1
            ],
            [
                17,
                -8,
                1
            ],
            [
                3,
                0,
                1
            ],
            [
                2,
                -1,
                1
            ],
            [
                2,
                -1,
                1
            ],
            [
                2,
                -1,
                0
            ],
            [
                1,
                0,
                1
            ],
            [
                3,
                -2,
                1
            ],
            [
                2,
                0,
                1
            ],
            [
                2,
                0,
                1
            ],
            [
                1,
                0,
                1
            ],
            [
                2,
                -1,
                1
            ],
            [
                3,
                -1,
                1
            ],
            [
                1,
                0,
                1
            ],
            [
                -189,
                26,
                6013
            ],
            [
                2,
                0,
                0
            ],
            [
                1,
                -1,
                1
            ],
            [
                0,
                0,
                2
            ],
            [
                1,
                0,
                0
            ],
            [
                1,
                0,
                2
            ]
        ],
        "keyUpCnt": 0,
        "keyUpValue": [],
        "mouseUpValue": [
            {
                "t": 853,
                "x": 222,
                "y": 292
            }
        ],
        "mouseUpCnt": 1,
        "mouseDownValue": [],
        "mouseDownCnt": 0,
        "orientation": [],
        "bSimutor": 0,
        "focusBlur": {
            "in": [],
            "out": [],
            "t": []
        },
        "fVersion": 0,
        "charSet": "UTF-8",
        "resizeCnt": 0,
        "errors": [],
        "screenInfo": "1920-1080-1050-24-*-*-*",
        "elapsed": 1000,
        "ft": "qf_7P_n_H",
        "coordinate": [
            10,
            63.99147415161133,
            0.5
        ],
        "clientType": "2",
        "trycnt": 5,
        "refreshcnt": 0,
        "slideValue": [
            [
                75,
                287,
                37
            ],
            [
                1,
                0,
                4
            ],
            [
                1,
                0,
                6
            ],
            [
                1,
                0,
                3
            ],
            [
                1,
                0,
                3
            ],
            [
                1,
                0,
                6
            ],
            [
                1,
                0,
                3
            ],
            [
                1,
                0,
                3
            ],
            [
                2,
                0,
                1
            ],
            [
                1,
                0,
                5
            ],
            [
                1,
                0,
                1
            ],
            [
                2,
                0,
                1
            ],
            [
                1,
                0,
                2
            ],
            [
                1,
                0,
                2
            ],
            [
                0,
                0,
                1
            ],
            [
                2,
                0,
                0
            ],
            [
                1,
                0,
                4
            ],
            [
                1,
                0,
                1
            ],
            [
                2,
                1,
                4
            ],
            [
                2,
                0,
                2
            ],
            [
                1,
                1,
                1
            ],
            [
                1,
                0,
                1
            ],
            [
                2,
                0,
                5
            ],
            [
                0,
                1,
                4
            ],
            [
                4,
                0,
                2
            ],
            [
                3,
                0,
                1
            ],
            [
                5,
                1,
                1
            ],
            [
                0,
                1,
                1
            ],
            [
                2,
                0,
                0
            ],
            [
                3,
                0,
                2
            ],
            [
                0,
                0,
                2
            ],
            [
                3,
                0,
                0
            ],
            [
                2,
                0,
                3
            ],
            [
                1,
                0,
                0
            ],
            [
                2,
                1,
                1
            ],
            [
                1,
                0,
                3
            ],
            [
                1,
                0,
                2
            ],
            [
                1,
                0,
                1
            ],
            [
                3,
                0,
                1
            ],
            [
                1,
                0,
                1
            ],
            [
                1,
                0,
                0
            ],
            [
                2,
                1,
                1
            ],
            [
                1,
                0,
                2
            ],
            [
                2,
                0,
                1
            ],
            [
                1,
                0,
                1
            ],
            [
                2,
                0,
                2
            ],
            [
                1,
                0,
                4
            ],
            [
                1,
                0,
                2
            ],
            [
                1,
                1,
                1
            ],
            [
                2,
                0,
                1
            ],
            [
                2,
                0,
                2
            ],
            [
                0,
                0,
                1
            ],
            [
                1,
                0,
                1
            ],
            [
                1,
                0,
                2
            ],
            [
                1,
                0,
                3
            ],
            [
                2,
                0,
                8
            ],
            [
                2,
                0,
                1
            ],
            [
                1,
                0,
                2
            ],
            [
                1,
                0,
                4
            ],
            [
                1,
                0,
                7
            ],
            [
                0,
                0,
                3
            ],
            [
                1,
                0,
                6
            ],
            [
                1,
                0,
                15
            ],
            [
                0,
                0,
                9
            ],
            [
                1,
                0,
                3
            ],
            [
                1,
                0,
                2
            ],
            [
                0,
                -1,
                2
            ],
            [
                1,
                0,
                3
            ],
            [
                0,
                -1,
                2
            ],
            [
                2,
                0,
                3
            ],
            [
                1,
                0,
                6
            ],
            [
                1,
                0,
                1
            ],
            [
                1,
                0,
                4
            ],
            [
                0,
                0,
                3
            ],
            [
                1,
                0,
                1
            ],
            [
                2,
                0,
                4
            ],
            [
                1,
                0,
                4
            ],
            [
                1,
                0,
                2
            ],
            [
                1,
                0,
                2
            ],
            [
                1,
                0,
                1
            ],
            [
                2,
                -1,
                4
            ],
            [
                1,
                0,
                3
            ],
            [
                0,
                0,
                2
            ],
            [
                2,
                -1,
                3
            ],
            [
                1,
                0,
                3
            ],
            [
                1,
                0,
                3
            ],
            [
                1,
                0,
                0
            ],
            [
                1,
                0,
                2
            ],
            [
                2,
                0,
                4
            ],
            [
                1,
                0,
                21
            ],
            [
                1,
                0,
                1
            ],
            [
                4,
                0,
                2
            ],
            [
                1,
                0,
                1
            ],
            [
                1,
                0,
                2
            ],
            [
                1,
                0,
                6
            ],
            [
                1,
                0,
                1
            ],
            [
                1,
                0,
                2
            ],
            [
                1,
                0,
                2
            ],
            [
                0,
                0,
                4
            ],
            [
                1,
                0,
                2
            ],
            [
                1,
                0,
                1
            ],
            [
                1,
                0,
                8
            ],
            [
                1,
                0,
                2
            ],
            [
                2,
                0,
                1
            ],
            [
                1,
                0,
                1
            ],
            [
                1,
                0,
                3
            ],
            [
                2,
                0,
                3
            ],
            [
                0,
                0,
                87
            ],
            [
                1,
                0,
                10
            ],
            [
                0,
                1,
                6
            ],
            [
                1,
                0,
                1
            ],
            [
                1,
                0,
                2
            ],
            [
                1,
                0,
                3
            ],
            [
                0,
                1,
                2
            ],
            [
                1,
                0,
                2
            ],
            [
                1,
                0,
                2
            ],
            [
                1,
                0,
                1
            ],
            [
                1,
                0,
                2
            ],
            [
                1,
                0,
                4
            ],
            [
                1,
                1,
                1
            ],
            [
                1,
                0,
                1
            ],
            [
                1,
                0,
                1
            ],
            [
                1,
                0,
                2
            ],
            [
                1,
                0,
                1
            ],
            [
                1,
                0,
                3
            ],
            [
                1,
                0,
                1
            ],
            [
                1,
                0,
                2
            ],
            [
                0,
                1,
                2
            ],
            [
                1,
                0,
                1
            ],
            [
                1,
                0,
                1
            ],
            [
                0,
                0,
                16
            ],
            [
                1,
                0,
                1
            ],
            [
                2,
                0,
                1
            ],
            [
                2,
                0,
                72
            ],
            [
                1,
                0,
                20
            ],
            [
                1,
                0,
                24
            ],
            [
                1,
                0,
                10
            ],
            [
                1,
                0,
                5
            ],
            [
                1,
                0,
                1
            ],
            [
                0,
                0,
                4
            ],
            [
                1,
                0,
                1
            ],
            [
                1,
                0,
                5
            ],
            [
                1,
                0,
                1
            ],
            [
                1,
                -1,
                1
            ],
            [
                2,
                0,
                5
            ],
            [
                1,
                0,
                1
            ],
            [
                1,
                0,
                2
            ],
            [
                1,
                0,
                0
            ],
            [
                1,
                0,
                2
            ],
            [
                0,
                0,
                1
            ],
            [
                2,
                0,
                2
            ],
            [
                1,
                0,
                2
            ],
            [
                2,
                0,
                3
            ],
            [
                1,
                0,
                3
            ],
            [
                1,
                0,
                1
            ],
            [
                2,
                0,
                2
            ],
            [
                2,
                0,
                1
            ],
            [
                2,
                0,
                2
            ],
            [
                1,
                0,
                2
            ],
            [
                1,
                0,
                2
            ],
            [
                1,
                0,
                2
            ],
            [
                1,
                0,
                4
            ],
            [
                1,
                0,
                1
            ],
            [
                0,
                -1,
                22
            ],
            [
                -1,
                0,
                40
            ],
            [
                -1,
                0,
                430
            ],
            [
                -1,
                0,
                15
            ],
            [
                -1,
                0,
                16
            ],
            [
                0,
                1,
                287
            ],
            [
                0,
                0,
                95
            ]
        ],
        "dragobj": 0
    }
    for (var _0x266fcc in _0x508a9d) {
        if (!(_0x266fcc in _0x3f9b04)) {
            _0x1b0e23[_0x266fcc] = _0x508a9d[_0x266fcc];
        }
    }
    var _0x5e2264 = JSON['\x73\x74\x72\x69\x6e\x67\x69\x66\x79'](_0x1b0e23);
   // _0x18ea41();
    var _0x5797f3 = _0xc7a8('0x137');
    var _0x5142c3 = _0xc7a8('0x137');
    _0x5797f3 = _0x23fd31['\x65\x6e\x63'][_0xc7a8('0x3e')][_0xc7a8('0x0')](_0x5797f3);
    _0x5142c3 = _0x23fd31['\x65\x6e\x63']['\x55\x74\x66\x38'][_0xc7a8('0x0')](_0x5142c3);
    var _0x22a8dc = _0x5e2264;
    var _0x73991 = 0xf - _0x22a8dc[_0xc7a8('0x15')] % 0x10;
    for (i = 0x0; i < _0x73991; i++) {
        _0x22a8dc += '\x20';
    }
    var _0x164c66 = _0x23fd31[_0xc7a8('0x94')][_0xc7a8('0x8d')](_0x22a8dc, _0x5797f3, {
        '\x69\x76': _0x5142c3,
        '\x6d\x6f\x64\x65': _0x23fd31['\x6d\x6f\x64\x65'][_0xc7a8('0x76')],
        '\x70\x61\x64\x64\x69\x6e\x67': _0x23fd31[_0xc7a8('0x7e')][_0xc7a8('0x77')]
    });
    return _0x826648 ? encodeURIComponent(_0x164c66[_0xc7a8('0x32')]()) : _0xc7a8('0x138') + encodeURIComponent('\x3c\x25\x3d\x73\x69\x74\x65\x4b\x65\x79\x25\x3e') + _0xc7a8('0x139') + encodeURIComponent(_0x164c66['\x74\x6f\x53\x74\x72\x69\x6e\x67']());
};

setData({trycnt: 6, refreshcnt: 0, slideValue: arr, dragobj: 0})
getData(1)